name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "381195f90d56069a337d7299cfb266d085ae835c90ba9aad651c5afa7497e595"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
