name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ac981b614f2475f6869b71c733bc116199f9136254dcd0fc514fe36065ed79"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
