name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf5b71bf4029091b4f854b8c2ba7c14c7013c0ad5ccb99bce105cd663a0d693"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
