name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50cf1d98ee1742cfe2046e856d5e35e9628294fe907f71040d6fdf5fba587eec"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
