name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "287c600c81fdfe835d07befce6e1982b953130b4f2c473415f98b9a1d4060558"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
