name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11676ba12ea1349cfddad4f2e993e093d66eb58508fcda2ad81b9e5d2ad14d5b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
