name = "The Bonked Minecraft"
author = "slowest____side"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01aa5a3634661dce3800da0af22a8662dfb7e0290640078226e19cb4846b9ac"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
